In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import *
import itertools
import gc

pd.options.display.max_columns = None

In [3]:
features_for_clustering = ['loan_rate', 'credit_score', 'desired_amount', 'birth_year', 'loan_limit', 'yearly_income']

In [4]:
df = pd.read_csv('../input/big-contest/data_0.csv')
df[features_for_clustering].describe().apply(lambda s: s.apply('{0:.2f}'.format))

,loan_rate,credit_score,desired_amount,birth_year,loan_limit,yearly_income
count,2.433613e+06,2.433613e+06,2.433613e+06,2.433613e+06,2.433613e+06,2.433613e+06
mean,1.271932e+01,7.504158e+02,5.184606e+07,1.982874e+03,2.278597e+07,4.821432e+07
std,3.879656e+00,1.221302e+02,2.300408e+08,9.532706e+00,2.249679e+07,1.280584e+08
min,1.500000e+00,-5.911000e+02,0.000000e+00,1.935000e+03,0.000000e+00,0.000000e+00
25%,9.500000e+00,6.500000e+02,1.000000e+07,1.977000e+03,9.000000e+06,3.000000e+07
50%,1.310000e+01,7.312000e+02,3.000000e+07,1.984000e+03,1.800000e+07,3.700000e+07
75%,1.560000e+01,8.439000e+02,5.000000e+07,1.990000e+03,3.300000e+07,5.000000e+07
max,2.000000e+01,1.957200e+03,1.000000e+10,2.003000e+03,1.000000e+10,1.000000e+10

In [ ]:
def cluster(data, n_clusters, clustering_feature, n_features):
    feature_names = ', '.join(clustering_feature)
    
    X = data[clustering_feature]
    
    print(f'=========={feature_names}==========')
    
    ms = KMeans(n_clusters=n_clusters, random_state=42)
    clustered = ms.fit_predict(X)
    
    data['cluster'] = clustered
    print(data['cluster'].value_counts())

In [ ]:
clustering_features = list(itertools.combinations(features_for_clustering, 3))
clustering_features = [list(t) for t in clustering_features]
clustering_features.sort()
print(len(clustering_features))

In [ ]:
plt_df = df.sample(100000).copy()
plt_df_idx = plt_df.index

In [ ]:
for cf in clustering_features:
    cluster(df, 3, cf, 3)
    
    fig, axes = plt.subplots(3, 3, figsize=(12, 12))
    
    plt_df = df.iloc[plt_df_idx].copy()

    for i, f_x in enumerate(cf):
        for j, f_y in enumerate(cf):
            if i == j:
                continue
            else:
                axes[i][j].scatter(plt_df[f_x], plt_df[f_y], c=plt_df['cluster'])
                axes[i][j].set_xlabel(f_x)
                axes[i][j].set_ylabel(f_y)
    plt.show()